USE master
GO

--drop database if it exists
IF DB_ID('final_capstone') IS NOT NULL
BEGIN
	ALTER DATABASE final_capstone SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE final_capstone;
END

CREATE DATABASE final_capstone
GO

USE final_capstone
GO

--create tables
CREATE TABLE users (
	user_id int IDENTITY(1,1) NOT NULL,
	username varchar(50) NOT NULL,
	password_hash varchar(200) NOT NULL,
	salt varchar(200) NOT NULL,
	user_role varchar(50) NOT NULL,
	zip varchar(20) NOT NULL,
	first_name varchar(100),
	last_name varchar(100),
    email varchar(100),
	CONSTRAINT PK_user PRIMARY KEY (user_id)
);

CREATE TABLE plants (
	plant_id int IDENTITY (1,1) NOT NULL,
	common_name varchar(50) NOT NULL,
	description varchar(1000),
	square_area decimal NOT NULL,
	cost decimal NOT NULL,
	sun_requirements varchar(50) NOT NULL,
	image_url varchar(500),
	temporary_usda_zones varchar(30)

	CONSTRAINT PK_plants PRIMARY KEY (plant_id)
);


CREATE TABLE hardiness (
	zone_id int IDENTITY (1,1),
	zone_name varchar(10),
	avg_last_frost_month varchar(10),
	avg_last_frost_day int,
	avg_first_frost_month varchar(10),
	avg_first_frost_day int,
	avg_growing_days int,
    CONSTRAINT PK_hardiness PRIMARY KEY (zone_id)
);


INSERT INTO hardiness (zone_name, avg_last_frost_month, avg_last_frost_day, avg_first_frost_month, avg_first_frost_day, avg_growing_days) VALUES ('3', 'May', '15', 'September', '15', '123');
INSERT INTO hardiness (zone_name, avg_last_frost_month, avg_last_frost_day, avg_first_frost_month, avg_first_frost_day, avg_growing_days) VALUES ('4', 'May', '15', 'October', '1', '139');
INSERT INTO hardiness (zone_name, avg_last_frost_month, avg_last_frost_day, avg_first_frost_month, avg_first_frost_day, avg_growing_days) VALUES ('5', 'May', '1', 'October', '15', '168');
INSERT INTO hardiness (zone_name, avg_last_frost_month, avg_last_frost_day, avg_first_frost_month, avg_first_frost_day, avg_growing_days) VALUES ('6', 'Apr', '15', 'October', '15', '183');
INSERT INTO hardiness (zone_name, avg_last_frost_month, avg_last_frost_day, avg_first_frost_month, avg_first_frost_day, avg_growing_days) VALUES ('7', 'Apr', '1', 'October', '31', '213');
INSERT INTO hardiness (zone_name, avg_last_frost_month, avg_last_frost_day, avg_first_frost_month, avg_first_frost_day, avg_growing_days) VALUES ('8', 'March', '15', 'November', '15', '245');
INSERT INTO hardiness (zone_name, avg_last_frost_month, avg_last_frost_day, avg_first_frost_month, avg_first_frost_day, avg_growing_days) VALUES ('9', 'February', '15', 'November', '30', '290');
INSERT INTO hardiness (zone_name, avg_last_frost_month, avg_last_frost_day, avg_first_frost_month, avg_first_frost_day, avg_growing_days) VALUES ('10', 'January', '1', 'December', '31', '290');
INSERT INTO hardiness (zone_name, avg_last_frost_month, avg_last_frost_day, avg_first_frost_month, avg_first_frost_day, avg_growing_days) VALUES ('11', 'January', '1', 'December', '31', '290');


CREATE TABLE farms (
	farm_id int IDENTITY (1,1) NOT NULL,
	user_id int NOT NULL,
	CONSTRAINT PK_farms PRIMARY KEY (farm_id),
	CONSTRAINT FK_farms_users FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE plots (
	plot_id int IDENTITY (1,1) NOT NULL,
	farm_id int NOT NULL,
	plot_name varchar(50) NOT NULL,
	sun_exposure varchar(15) NOT NULL,
	plot_square_footage decimal NOT NULL,
	zone_id int NOT NULL,

	CONSTRAINT PK_plots PRIMARY KEY (plot_id),
	CONSTRAINT FK_plots_farms FOREIGN KEY (farm_id) REFERENCES farms(farm_id),
	CONSTRAINT FK_plots_zones FOREIGN KEY (zone_id) REFERENCES hardiness
);

CREATE TABLE plots_plants (
	plots_plants_id int IDENTITY (1,1),
	plot_id int,
	plant_id int

	CONSTRAINT PK_plots_plants_id PRIMARY KEY (plots_plants_id)
	CONSTRAINT FK_plots_plants_plots FOREIGN KEY (plot_id) REFERENCES plots(plot_id),
	CONSTRAINT FK_plots_plants_plants FOREIGN KEY (plant_id) REFERENCES plants(plant_id)
)

CREATE TABLE supplies (
        supply_id int NOT NULL,
		description varchar(1000),
		image_url varchar(500),
        supply_name varchar(100) NOT NULL,
        supply_cost decimal NOT NULL,
        CONSTRAINT PK_supplies PRIMARY KEY (supply_id),
		--CONSTRAINT FK_supplies_farms FOREIGN KEY (farm_id) REFERENCES farms(farm_id)
);

CREATE TABLE supplies_farms(
	supply_id int,
	farm_id int,
	CONSTRAINT PK_supplies_farms PRIMARY KEY (supply_id, farm_id),
	CONSTRAINT FK_supplies_farms_supplies FOREIGN KEY (supply_id) REFERENCES supplies(supply_id),
	CONSTRAINT FK_supplies_farms_farms FOREIGN KEY (farm_id) REFERENCES farms(farm_id)
);

--default supply inserts
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('1', 'This premium wood mulch will protect and enhance your landscape with a natural, finished look. By creating a protective barrier around your plants and over soil. Natural wood composition controls weed growth, has excellent moisture retention properties and keeps a more even ground temperature to protect tender plants and roots.', 'https://www.ruralking.com/media/catalog/product/5/8/58aa61ed9ff0f3f9adf298ebcb639977f69dc794_80190105.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Brown Colored Mulch, 2 Cubic Feet', '2.49');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('2', 'Red Colored Mulch is a recycled product made from scrap pallets and virgin wood which is chip-ground into strips about ½" by 2-3 inches long and colored red. It does lose its color after about 2 years but a fresh annual cover keeps it looking red and vibrant.', 'https://www.ruralking.com/media/catalog/product/2/6/2603c6d24cef2ee51b111a6ce675119fa4dc3c34_80190095.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Red Colored Mulch, 2 Cubic Feet', '2.49');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('3', 'Black mulch is dyed with carbon. Natural wood composition controls weed growth, has excellent moisture retention properties and keeps a more even ground temperature to protect tender plants and roots.', 'https://www.ruralking.com/media/catalog/product/e/3/e3f6719f9690fec61d89f5cf347179e17d55f17f_80190107.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Black Colored Mulch, 2 Cubic Feet', '2.49');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('4', 'Enduring and intense, the Apex Farm and Ranch Hose is built for performance. This ranch hose is made from light vinyl and features a heavy-duty coil to prevent strain.', 'https://www.ruralking.com/media/catalog/product/d/8/d8a689f51fa0b87bdbb2ea7f2daa9337d8e49c1f_2840187_2840187_image_2840187.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Apex 5/8" x 100'' Farm and Ranch Duty Hose ', '34.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('5', 'Ready for bigger, more beautiful (vs. unfed plants) annuals, perennials and vegetables? Get plants off to a great start with Miracle-Gro Garden Soil All Purpose. Enriched with continuous release plant food, it feeds plants for up to 3 months and improves existing soil to help your plants build strong roots. This is the complete garden soil for all your outdoor, in-ground needs.', 'https://www.ruralking.com/media/catalog/product/8/4/84e32b603b2fa00d12bccb26c744d61cc2c33d99_19990526.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Miracle-Gro All-Purpose In-Ground Use Garden Soil, 1 cu. ft.', '5.49');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('6', 'Ready for bigger, more beautiful (vs. unfed plants) annuals, perennials and vegetables? Get plants off to a great start with Miracle-Gro Garden Soil All Purpose. Enriched with continuous release plant food, it feeds plants for up to 3 months and improves existing soil to help your plants build strong roots. This is the complete garden soil for all your outdoor, in-ground needs.', 'https://www.ruralking.com/media/catalog/product/2/1/215796db6e45ac7a978b288f18dbd08feadd22a4_19990524.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Miracle-Gro All-Purpose In-Ground Use Garden Soil, 2 cu. ft.', '11.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('7', 'Your plants want to show off. Give indoor and outdoor container plants the right ingredients to grow bigger and more beautiful with Miracle-Gro Potting Mix. Our specially formulated mix feeds for up to 6 months for more blooms and more color (vs. unfed plants). Use with indoor and outdoor container plants. Grows Plants Twice as Big (vs. unfed plants)!', 'https://www.ruralking.com/media/catalog/product/f/f/ff4c76ea2deffcfdd1d4ad8c926541732f1d38be_19990295.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Miracle-Gro Potting Mix, 1 Cu. Ft.', '8.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('8', 'Your plants want to show off. Give indoor and outdoor container plants the right ingredients to grow bigger and more beautiful with Miracle-Gro Potting Mix. Our specially formulated mix feeds for up to 6 months for more blooms and more color (vs. unfed plants). Use with indoor and outdoor container plants. Grows Plants Twice as Big (vs. unfed plants)!', 'https://www.ruralking.com/media/catalog/product/3/8/380947be302d8be472c4f83798708689e001277f_19990512.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Miracle-Gro Potting Mix, 2 Cu. Ft.', '12.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('9', 'Nubuck Palm for Abrasion Resistance. Foam Padding Provides Slight Impact Protection. Reinforced Thumb Saddle and Fingertips for Added Durability. Touch Screen Index Fingertip. Lightweight and Breathable. Machine Washable', 'https://www.ruralking.com/media/catalog/product/e/c/ec066b654679a3249c46bf4e270b097720d4f513_12930003.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'High Performance Work Gloves, 3 Pairs', '7.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('10', 'Motomco’s complete mole control program includes mole killer, a revolutionary mole bait, and Motomco’s new mole trap. Scientifically proven to kill moles, mole killer resembles their natural food - earthworms and grubs - in size, shape and feel. This breakthrough product was developed and tested on live, captured moles and contains special enhancers to attract moles. It kills in just a single feeding. Moles usually die in their tunnel, often within 12-24 hours of ingesting a single worm. Mole killer is EPA-approved for use by homeowners on lawns and gardens.', 'https://www.ruralking.com/media/catalog/product/f/f/ffb681c025ec482ac677f0facb3cf7beb143bc58_003890592_1_1.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Motomco Mole Killer Earthworm Formation, 8 Pack ', '21.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('11', 'This forged bow rake is high quality and designed for light-duty jobs around the lawn and garden. The tine side of the rake head is used to break up and cultivate the soil, while the back side of the rake is great for leveling soil and other materials.', 'https://www.ruralking.com/media/catalog/product/b/3/b3165ff6edbcbc7aea3aecb2fd9124675b2f9c2f_5071513_5071513_image_5071513.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Truper 14 Tine Welded Bow Rake', '8.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('12', 'The versatile two-sided bow rake is designed to loosen and level soil. The steel tines work hard to break up compacted soil or mulch, while the back of the rake head is good for leveling and smoothing. A great value for all your landscaping and gardening needs.', 'https://www.ruralking.com/media/catalog/product/a/5/a5eefc89b0621d32bb327f2d4229384288d4c827_10980013_10980013_image_10980013.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Truper 53" Fiberglass Bow Rake', '17.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('13', 'Sunniland Bahia Weed & Feed 20-0-6 provides season long broadleaf weed control for Bahia, Fescue, Bluegrass, Rye, Bermuda, Zoysia and Centipede grasses.', 'https://www.ruralking.com/media/catalog/product/b/c/bca3e021da996e723b19744f70685e927a79fc7c_18712003.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Sunniland Bahia 20-0-6 Weed & Feed, 20 Pounds', '16.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('14', '45-inch premium grade waxed hardwood handle for strength and economy. White Ash handles give optimum ratio of resistance and flexibility. 9-inch Cushion grip for improved control and reduced hand fatigue. Rolled step blade for secure foot placement it single rivet attaches . Well made for occasional use, at an affordable price.', 'https://www.ruralking.com/media/catalog/product/c/3/c3d2548c36a0d0adfb313dc5bea87145f99ff5cf_5070158_5070158_image_5070158.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Truper Tru Built Round Point Shovel', '9.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('15', 'Lightweight for extended use, the Truper Tru Pro 5-Tine Manure Fork features a fiberglass handle and a forged head with a rivet connection for added strength.', 'https://www.ruralking.com/media/catalog/product/f/4/f4eeb55799dfeb2e7101e20c90f9d1ae2d092797_10980039_10980039_image_10980039.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'TruPro 5 Tine Manure Fork with Fiberglass Handle', '27.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('16', '6 Cubic Foot Poly Wheelbarrow. Box Steel Handles with Rugged Grips', 'https://www.ruralking.com/media/catalog/product/0/a/0aaa0395c0dc06acd128efb9ddc9e44a48881144_33550002.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', '6 Cubic Foot Poly Wheelbarrow', '79.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('17', 'High carbon steel Teflon-S coated blade, die-cast aluminum handle with PVC grip thumb lock', 'https://www.ruralking.com/media/catalog/product/7/3/73960ad4645467b03c340dcecec7701cf62a7495_5070747_5070747_image_gbpp_8.5.jpg.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'SMV Industries 8.5 inch Bypass Pruner', '7.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('18', 'This easy-to-use, true dual-rotation garden cultivator delivers unmatched ground breaking and garden prep in any soil type. With a forward rotation for cultivation and a counter rotation for deep soil tilling, the high-powered engine delivers optimal torque and rotational speed. Convenient, single-hand operation of this soil tiller allows users to stand and steer from either side, while the self-propelled drive system offers enhanced control.', 'https://www.ruralking.com/media/catalog/product/e/a/ea71b445667e5c925d3a2df51126ecbf09474150_60048029.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Yardmax 208cc Dual Rotating Rear Tine Tiller', '729.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('19', 'Ideal for cutting, weeding, and turning tough soil around your lawn and garden', 'https://www.ruralking.com/media/catalog/product/4/a/4a82e75bbc0e5f3c9cba6f5875677a06ef40b82e_5071623_5071623_image_5071623.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Truper Garden Hoe', '13.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('20', 'All Purpose 12-12-12 Fertilizer contains a balance of nutrients for added greening power. Formulated to help disease resistance and thickens new and existing lawns. It is easy to use and produces vibrant growth from tender beginnings, producing a resilient turf. We also recommend Greenskeeper''s Secret All Purpose Fertilizer for Vegetables, flowers, fruit, nut and shade trees and hardy evergreens and shrubs. For best results, use according to the following directions and water thoroughly after each application.', 'https://www.ruralking.com/media/catalog/product/7/2/72bb7fee519e624e885592be8cf87cf53327a1d8_69840146.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Secret All-Purpose 12-12-12 Fertilizer', '12.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('21', 'From the moment you pick it up, you’ll notice this watering nozzle is different. Designed with mobility in mind, it includes Gilmour’s innovative Swivel Connect™ feature. The swivel allows the nozzle to pivot without twisting the hose, thus reducing the likelihood of kinking.', 'https://www.ruralking.com/media/catalog/product/8/b/8bf001db8c060db8f0660be6dc1861a62b109c63_2890786_2890786_image_2890786.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Gilmour Front Control Watering Nozzle with Swivel Connect', '7.93');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('22', 'EZRead rain gauges and thermometers are both accurate and easy-to-read and can be used indoors or outside. From -40 to 140 degrees and 10 inches of rain, we have the thermometer or rain gauge to suit your needs.', 'https://www.ruralking.com/media/catalog/product/9/d/9df7c40b1a84a9bd0572af5f83cdf7ea10c88dbd_1850026.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Read Classic Jumbo Rain Gauge', '9.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('23', '54'' lacquered ash handle', 'https://www.ruralking.com/media/catalog/product/9/3/938c40921df1071d19abe94fbc15121af5646893_5072428_5072428_image_5072428.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', '10 Tine Manure Bedding Fork', '28.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('24', '3 Forks on one side', 'https://www.ruralking.com/media/catalog/product/1/9/194a157a3c71ac060d83dd63e76d7fa3f09e444e_005070909.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Tine Fork & Hand Hoe', '4.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('25', 'Ideally Used for salt/ice melt, fertilizer, seeds and some kinds of crops.', 'https://www.ruralking.com/media/catalog/product/3/b/3b1255e8ccc2ec4aad70eb3e4a5c5cf46eba3dad_33780001.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Broadcast Spreader', '44.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('26', 'Rivet less steel ring that connects the shovel neck and handle making it one solid unit', 'https://www.ruralking.com/media/catalog/product/7/b/7ba040d4c47f25156cbe32d74d225de3a02cf4b2_5070093_5070093_image_5070093.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Round Point Shovel', '21.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('27', 'Lacquered handle for strength and durability. Hoe weeds up by the roots. Clear-coated gray-steel finished heads.', 'https://www.ruralking.com/media/catalog/product/1/8/18ec235a474609ec60297f35c5060d23e7f98282_5072211_5072211_image_5072211.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Forged Heavy Duty Scraper with Long Handle', '24.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('28', '50C Carbon steel blade with Teflon coating wood/rubber handles PVC grips', 'https://www.ruralking.com/media/catalog/product/0/f/0ff9b88ed378778104af17219ecf6fe8a5209321_5070828_5070828_image_gbls_28.jpg.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', '28 inch Bypass Lopping Shear', '17.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('29', 'Agri-Fab 85 lb. Tow Spreader is a good choice when you need to start, re-start or weed and feed your lawn, spread everything from fertilizer to seed to ice melt with this spreader.', 'https://www.ruralking.com/media/catalog/product/7/5/751eeed8c98414d3543e8be1660d38f13bee9bf0_66880248.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', '85-lb Tow Spreader', '119.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('30', '3 pronged cultivator', 'https://www.ruralking.com/media/catalog/product/4/c/4c26dc3adab4cf0179138d9a3e8406c2314338b7_005070925.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Hand Cultivator', '4.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('31', 'Pinned and forged head with 4 tines', 'https://www.ruralking.com/media/catalog/product/0/0/00cf576c8448c7e4ed111ac83c185716cf9be1a2_10980505_10980505_image_10980505.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', '4 Tine Forged Cultivator with Fiberglass Handle', '21.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('32', 'Box Steel Handles with Rugged Grips', 'https://www.ruralking.com/media/catalog/product/f/2/f2291753be0b3a1bbae9bde00a00465d3e5e7b25_33550004.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Cubic Foot Steel Wheelbarrow', '109.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('33', '54" wood handle, 5" forged warren hoe', 'https://www.ruralking.com/media/catalog/product/f/2/f2e28492d99a842a8a6b74105474770494bfdcc6_5071678_5071678_image_5071678.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Forged Warren Hoe with Ash Handle', '27.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('34', 'Blade Extends Completely Through the Wood Handle', 'https://www.ruralking.com/media/catalog/product/b/o/bond_manufacturing_16_in._corn_knife_6218.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Manufacturing 16 in. Corn Knife', '13.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('35', 'Sharp blade for quick and easy pruning. Extra sharp blades that cut small limbs fast. Clean and oil after each use for years of trouble free use. Cut pathways and trails through jungle vines and your own back yard.', 'https://www.ruralking.com/media/catalog/product/0/5/051abfa79efacc805fe2b2f9ff95bea81694d00f_25200054.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', '18-Inch Double Edge Machete Garden Saw', '14.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('36', 'This soil scoop is lightweight for easy handling and durable for lasting value. A generous scoop helps you get more done faster, and a single-piece, rustproof FiberComp design will never loosen or bend. In addition, a handle hang hole makes storage convenient.', 'https://www.ruralking.com/media/catalog/product/c/a/cae3a9f99a49f0624133c80c719c21441692f381_5420368_5420368_image_5420368.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Soil Scoop', '1.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('37', 'With a commercial-grade gearbox and easy-set controls, the Agri-Fab, Smart Spreader 130 lb. Tow Spreader is designed to be towed by a lawn tractor in order to spread ice melt, fertilizer and seed up to a 12 ft. spread width.', 'https://www.ruralking.com/media/catalog/product/5/f/5fb3cf2acecdc634a6002539ff65c99040c73150_66881496.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', '130-lb Tow Spreader', '249.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('38', 'PowerGear® is a patented gear technology multiplies leverage to give you up to 3X more power on every cut! It powers through thick branches that traditional loppers and pruners can’t. Patent-pending design with modified gears and cam mechanism optimizes your cutting power in the middle of the cut where the branch is thickest and you need it most.', 'https://www.ruralking.com/media/catalog/product/8/8/88c90a614de6f5d45685e649d7185d038001d2cb_5420070.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Large Bypass Lopper', '49.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('39', 'Luster Leaf''s Mini Seedmaster makes sure small seeds are planted exactly where you want them with this small plunger-type dispenser. It reduces waste and the amount of thinning. This plastic seed dispenser allows you to plant tiny seeds like radish, carrot, lettuce and others with less waste and more precision. It''ll also reduce the amount of time spent thinning seedlings—a task that can disturb the roots of the seedlings you want to keep.  The small, plunger-type dispense is made of sturdy plastic.', 'https://www.ruralking.com/media/catalog/product/7/b/7b4edf8096c6b9169ceb1b5f9497bbda1db9e327_22880212_22880212_image_805_wo_pack.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Luster Leaf Rapiclip Mini Seedmaster', '2.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('40', 'Durable stainless steel blades. Self-sharpening serration blade.', 'https://www.ruralking.com/media/catalog/product/1/c/1c62769fffa99de49480c9502e5d6fdbe7355e5f_005070789.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Grass Shears 12.5 inch', '9.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('41', 'Strap yourself in & make spraying a breeze with the Master Manufacturing 4 gallon backpack sprayer.', 'https://www.ruralking.com/media/catalog/product/8/5/85d7dd7b5ab71d9d59756cd2b4b79eae97199969_7813636.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', '4 Gallon Backpack Sprayer', '69.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('42', 'This Maple Ridge steel rake is used for clearing leaves and debris from lawns. The flexible steel tines of the garden rake will pull out thatch for a healthier lawn. The one-piece steel head of the leaf rake is attached to the handle for a secure connection while raking. The leaf rake also features a sturdy wooden handle.', 'https://www.ruralking.com/media/catalog/product/5/8/5847841c868bff3846c8ac9edd979651e0d68275_33580002.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Maple Ridge 30" Metal Rake with Wooden Handl', '12.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('43', 'Extra-large removable lid allows easy access for filling and dumping. With your compost ingredients enclosed inside the composter tub, you will not be subjected to an unsightly, smelly, fly attracting, open-air compost heap.', 'https://www.ruralking.com/media/catalog/product/a/3/a38c42c3f24ca6c7c086bc865a14f9e2b6640b26_lifetime_65_gallon_compost_tumbler.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', '65 Gallon Compost Tumbler', '169.97');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('44', 'Composting lets you turn yard waste and kitchen scraps into homemade garden compost. Composting is Nature''s perfect recycling plan. The Gronomics Solar Assist Composter allows the waste to breakdown efficiently by letting the sunlight pass through the transparent roof. The Composter is made of 100% Western Red Cedar and features rust resistant wire for side panels. The corrugated poly roof is hinged which allows easy access from either side and is virtually unbreakable.  It is light bronze in color for UV protection and offers solar heating insulation.  The composter holds 9 cubic feet of compostable material and features tool free assembly which simply slides together in minutes.', 'https://www.ruralking.com/media/catalog/product/f/6/f6939efef326cd225b0d45ca2f4869df0f8a6898_gronomics_small_solar_assist_composter_sac_24_45_3.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Small Solar Assist Composter', '349.97');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('45', 'Multi-purpose glove great for everyday jobs. Latex double-dipped formed glove. Breathable and comfortable. Provides grip in wet or dry conditions. Nylon/spandex used on the back of the hand for a better, tighter fit. Constructed of 7 gauge yarn for more comfort and faster drying.', 'https://www.ruralking.com/media/catalog/product/d/5/d5d2d7b0274a83243fa7bb05cab5d417de6ee605_49181974.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Grip Work Gloves - X-Large', '8.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('46', 'Heavy-Duty Steel, Double Bolted.', 'https://www.ruralking.com/media/catalog/product/7/b/7b67a7d8fca282ca8155194fc9c8dfd559e7e612_63290077_63290077_image_87610.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Industrial Brush Cutter', '35.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('47', 'Support tomatoes, peppers and other plants with these 16 x 42". Heavy Duty Inverted Plant Supports. Featuring 3/16" American galvanized wire, this cage will look great and resist rust for years of use.', 'https://www.ruralking.com/media/catalog/product/b/9/b9369040255c0157a830c825be751e1b6d81fe6d_53670144_53670144_image_53670144.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Heavy Duty Galvanized Inverted Support', '4.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('48', 'Black Kow 50 lb. Composted Cow Manure is an organic soil amendment for vegetable gardens, flower beds, lawns and landscapes. It is a natural organic product that is aerobically composted and adds millions of beneficial microbes to enhance the soil structure and promote healthy plant growth. Black Kow has a 0.5-0.5-0.5 fertilizer analysis and provides nutrients for your flowers and vegetables', 'https://www.ruralking.com/media/catalog/product/b/e/beb0a5a3a1290b3df8b310b3f67fce37c392a30f_197330814.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Black Kow Mushroom Compost', '5.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('49', 'Instantly tells you how acid or alkaline your soil is. Check which plants suit your garden. Enables you to alter soil conditions.', 'https://www.ruralking.com/media/catalog/product/0/b/0bee3e2ad4df0663ba85ac7e6c9414304aa0c2d3_022880033.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'Rapitest PH Meter Battery Powered', '9.99');
INSERT INTO supplies (supply_id, description, image_url, supply_name, supply_cost) VALUES ('50', 'The modular raised garden bed is designed to easily expand with your garden needs and to create unlimited multi-level designs. Modular raised garden beds are ideal for small plots of vegetables and/or flowers. With these beds you eliminate tilling, soil amending, and minimize weeding. They are quick and easy to assemble plant and maintain. Easily adapt square foot gardening techniques to these beds. The rough sawn rustic appearance looks great in any setting. 100% Western red cedar.  Handcrafted in the USA!!', 'https://www.ruralking.com/media/catalog/product/f/7/f7ef92d365092778d2add47edd7faa905e67526f_gronomics_raised_one_level_modular_raised_garden_bed_mrgb_1l_48_48_4.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=560&width=700&canvas=700:560', 'One Level Modular Raised Garden Bed', '64.97');


--default user inserts
INSERT INTO users (username, password_hash, salt, user_role, zip) VALUES ('user','Jg45HuwT7PZkfuKTz6IB90CtWY4=','LHxP4Xh7bN0=','user', 44406);
INSERT INTO users (username, password_hash, salt, user_role, zip) VALUES ('admin','YhyGVQ+Ch69n4JMBncM4lNF/i9s=', 'Ar/aB2thQTI=','admin', 44512);

--because user's farm will be assigned at registration, these /\ /\ /\ default users are assigned their farms here\/ in the sql query.
INSERT INTO farms (user_id) VALUES ((SELECT user_id FROM users WHERE username LIKE 'user'));                   -- < < <
INSERT INTO farms (user_id) VALUES ((SELECT user_id FROM users WHERE username LIKE 'admin'));                  -- < < <

INSERT INTO plants (common_name, description, square_area, cost, sun_requirements, image_url, temporary_usda_zones) VALUES
('Anise', 'Anise is an annual/biennial herb that produces little, dainty white flowers and seed that has a refreshing licorice flavor. The small 1.5-2 feet tall plants have feather like green leaflets that are great for making aromatic tea. Anise seed produced from the plants can be used whole or ground in doughs or fillings of baked goods or brewed to make a delicate licorice-flavored tea', 1, 3.00, 'sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwe4f23339/images/products/Pimpinella-anisum_flower.jpg?sw=450&sh=450','3,4,5,6,7,8,9'), 
('Artichoke-Green Globe', 'The Green Globe is America''s most popular artichoke! Large flower buds, harvest when plump, ornamental with bold blue 6" flowers. Artichokes are a very tender plant. With thick, fleshy scales and solid center, the flower heads should be harvested when they''re young. Native to the Mediterranean, globe artichokes have been grown in the US since Colonial times. Provided with a protective cover, the artichokes will successfully overwinter in colder areas.', 4, 3.00,'sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwb8c5d6cf/images/products/Artichoke_Seed1.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Artichoke-Violet', 'Violet is a French heirloom with fine flavor! Beautiful purple buds that are lovely on the big, ornamental plants, especially when the buds open. Rare outside Europe.', 4, 3.00, 'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwb05414b4/images/products/Violet-Artichoke-Seed.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),  
('Artichoke-Jerusalem', 'A high yielding delicious tuber! Jerusalem Artichokes, aka Sunchokes, are great for winter markets as they store well. A carefree plant that produces heavy yields of tubers. Stampede is early producing giving you a jump on other growers. They store well and can be eaten raw or cooked. Winter hardy in severe cold. Grows fast and should be given room to grow.', 1, 3.00, 'sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw6f108f88/images/products/Jerusalem-Artichokes.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Asparagus-Purple Passion', 'Purple Passion is a fun and colorful asparagus to grow. This dark purple asparagus roots are a perennial that can be planted just once and the succulent spears can be enjoyed for years. A very nutritious and delicious vegetable to have in your garden.', 1.5, 3.00, 'sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw12f89fa1/images/products/Purple-Passion-Asparagus.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Asparagus-Jersey Knight', 'The Jersey Knight asparagus is a very productive and great tasting plant. These roots grow tall stalks that can yield up to 3-4 times more asparagus than other varieties. Predominantly male, produces high yields, high disease tolerance and produces well in warmer climates. Jersey Knight produces the best spear quality of all the Jersey hybrids. Green spears with purple bracts.', 1.5, 3.00, 'sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw5a261816/images/products/Jersey_Knight_Asparagus.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Basil-Dark Opal', 'The Dark Opal Basil is a unique, wonderfully delicious tasting, purple colored basil that is popular for micro green production! These mostly purple plants, with 20% variegated or green plants, make for a beautiful color combo. The Dark Opal''s leaves average at 1 1/2-3" at full size.', 1, 3.00, 'part-shade', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw3e9f4569/images/products/Purple_Basil_Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Basil-Holy', 'Holy basil (Ocimum tenuiflorum) is a plant that is native to India. It is commonly used in the traditional Indian medicine system, Ayurveda. Holy basil is sometimes called "hot basil" because of its peppery taste. Chemicals in holy basil are thought to decrease pain and swelling.', 1, 3.00, 'part-shade', 'https://cdn.shopify.com/s/files/1/0614/3796/8618/products/1639414251_basil-holy-green-leaf-com-wm_1512x.jpg?v=1639680009', '3,4,5,6,7,8,9'),
('Basil-Thai', 'The Thai Basil is a highly ornamental and fragrant variety that produces deep green leaves with beautiful purple stems and blossoms. This variety has a distinctive flavor combination of cloves and mint with a delicate sweetness. You can use both its leaves and flowers in recipes as well as a garnish.',1, 3.00, 'part-shade', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw7f4fad2d/images/products/Thai-Basil.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Bee Balm', 'The Panorama Bee Balm is a great cutting plant for center pieces. This beautiful flower blooms from July to August on 3'' foot plants. This bee balm prefers full sun or afternoon shade.', 1.5, 3.00, 'sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwc3288551/images/products/Wild-Bergamot.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Borage', 'Borage is a mounded plant that produces beautiful blue flowers that are great for using as a garnish for different dishes or drinks. This large variety is a self seeding annual that bears hundreds of small edible flowers, mostly blue and some pink, over a long harvest. Borage has a mild cucumber flavor that is great for salads and garnishes. Medicinal: Seed oil is a rich source of gamma-linolenic acid.', 1, 3.00, 'sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwf867b1c0/images/products/Borage-Seed.jpg?sw=450&sh=450','3,4,5,6,7,8,9'),
('Caraway', 'Caraway is a biennial herb that produces smooth, finely cut green leaves with little delicate and fragrant white flowers. This furrowed stem plant produces edible flowers and roots. Caraway has a delicious unique flavor that is great to use in baking and preserving.', .5, 3.00, 'sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw94c7107a/images/products/Caraway.jpg?sw=450&sh=450','3,4,5,6,7,8,9'),
('Catnip', 'Catnip is a very fragrant herb that is great for making aromatic teas, as well as giving it to your cats as a treat! This vigorous plant is not only great for playing with a cat, but is also known for having medicinal properties for getting rid of the cold and flu', 1.5, 3.00, 'sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwec269b71/images/products/Catnip.jpg?sw=450&sh=450','3,4,5,6,7,8,9'),
('Chamomile', 'Chamomile is an herb that produces an abundance of small, fragrant daisy-like white flowers that are used in making teas and perfumes. This herb is used to aid in digestion and act as a gentle sleep inducer. You can also use its flowers to garnish desserts or drinks.', .5, 3.00, 'part-shade', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw6a64af2e/images/products/Chamomile.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Chervil', 'The Plain Leaf Chervil resembles Italian parsley in appearance, but has a stronger, sweeter flavor that is often paired with tarragon, chives and parsley. This Brussels winter type is a vigorous plant with a subtle warm flavor that is excellent in fish and chicken dishes or light sauces and dressings.', .5, 3.00, 'part-shade', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwcc92e7ec/images/products/Chervil_Plain_Leaf.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Chive', 'The Chive is a widely known herb that produces flat, solid leaves with a wonderfully pungent flavor that is similar to onions. This plant can grows as high as 1.5'' feet and 12" inches wide.', .5, 3.00, 'sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwf76c40e9/images/products/Organic-Standard-Chives.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Cilantro', 'The highly aromatic, rich and spicy Cilantro adds the perfect flavor to any cuisine! This plant is ideal for harvesting both the cilantro leaves and coriander seeds.The unique flavor of this cilantro is bold and bright with a touch of citrus undertones. Cilantro is the perfect herb for a patio container or herb kit in a window sill, sow every ten days for a continuous harvest.', .5, 3.00,'part-shade','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw1d47d756/images/products/Organic-Common-Cilantro.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Comfrey', 'Comfrey is a hardy, drought tolerant plant that is easy to start from seed. A clumping herb comprised of multiple stalks, prefers well drained soil and full sun to partial shade. Grows between 36-48 inches. Comfrey will put nutrients into the soil, mulch trees, and shrubs, prevent weeds, feed livestock, attract beneficial pollinators, and make quick compost tea.',9, 3.00, 'part-shade','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwea4cf4c3/images/products/Comfrey%20Seeds.png?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Cumin', 'The beautiful blush, pink flowers of the wonderfully fragrant Cumin plants are used to flavor many popular East Indian dishes! The beautiful foliage has a very aromatic smell that is similar to dill. This herb''s young leaves mix very well into salads. Cumin grows best in warmer climates, but will produce seeds in cooler northern climates if started early enough.', .5, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw6e34aa26/images/products/Cumin-Seed.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Dill', 'Dill has a warm, slightly sharp flavour somewhat reminiscent of caraway. The entire plant is aromatic, and the leaves, small stems, and immature flower umbels are used fresh or dried for flavouring soups, salads, sauces, fish, sandwich fillings, and particularly pickles.', .5, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwb76be47f/images/products/Dill-Mammoth.jpg?sw=275&sh=275','3,4,5,6,7,8,9'),
('Hyssop', 'Hyssop is a popular ornamental herb in the mint family that is great for attracting bees and other beneficial insects to the garden. This herb produces bright blue to violet flowers that are used to make a soothing tea. You can harvest the flowers in midsummer and hang them upside down under shade to dry.', .5, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw9179f6d7/images/products/Hyssop.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Lavender', 'Lavender plants are small, branching and spreading shrubs with grey-green leaves and long flowering shoots. The leaves can be simple or pinnate measuring 1–2 inches in length. The plant produces flowers on shoots or spikes which can be 8–16 inches long. The flowers are lilac or blue in color.', 4, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw0ab9b37a/images/products/Lavandula_angustifolia.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Lemon Balm', 'Lemon Balm is a wonderfully aromatic herb that is used for flavorings and teas! This variety can grow up to 2 feet-tall. Lemon Balm will bloom beautiful fragrant white flowers that are great for attracting bees to your garden for pollination.', 1.5, 3.00,'part-shade','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwb087dcd5/images/products/Lemon-Balm-Seeds.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Lemon Grass', 'The deliciously fresh, citrus lemon flavor of the Lemongrass is a very popular herb variety for its many different culinary uses. This lemongrass variety can be used to flavor teas, beverages, soups, and many other dishes. The lemongrass plant can reach up to 6 feet tall.', 9, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw1c950563/images/products/Lemon_Grass.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Lovage', 'Lovage is a popular culinary herb that produces fine, dark green leaves that have an aroma and taste that is similar to celery. Its leaves can be used in salads, soups as well as added to poultry dishes. The Lovage''s roots and stems are also edible. The yellow flowers that this herb produces in June to July attract beneficial insects such as bees.', 1, 3.00,'part-shade','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwbb806bce/images/products/Lovage.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Bean-Bush', 'Bush beans are second only to tomatoes as the most popular vegetables in home gardens. Bush beans, or snap beans, grow on a rounded, shrub-shaped plant. The pods are eaten when the seeds are small. They are also called string beans because of a fibrous string running the length of the pod, but most varieties grown now do not have that fibrous string.', .5, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwb4ef3204/images/products/Blue-Lake-Bush-Beans.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Bean-Fava', 'Fava beans grow in big, bumpy green pods on an easy-to-grow flowering pea plant that is harvested in the spring. Inside the cushy pods are large, flat, bright green beans with a tough, clear skin that is typically removed before eating.', .5, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw6e52a8cc/images/products/Fava-Windsor-Bean-Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Bean-Pole', 'Fresh, crisp beans are summer treats that are easy to grow in most climates. Beans may be pole or bush, however, growing pole beans allows the gardener to maximize planting space. Planting pole beans also ensures a longer crop period and may yield up to three times as many beans as the bush varieties. Pole beans require some training onto a pole or trellis, but this makes them easier to harvest and the graceful flowering vines add dimensional interest to the vegetable garden.', .5, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw06b2ea19/images/products/White-Yard-Long-Beans.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Bean-Soy', 'Soybeans are healthful and rich in protein, giving them numerous nutritional uses. People can eat them, drink them in milk alternatives, and take them in the form of supplements.', .5, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw4ac230f4/images/products/Kentucky_Wonder_Beans.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Beet', 'Beets—or “beet roots”—are a colorful, cool-season crop that is easy to grow from seed in well-prepared soil and grows quickly in full sun. They are a great choice for northern gardeners because they can survive frost and near-freezing temperatures. This also makes them great as a fall crop.', .5, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw3aaffe36/images/products/Lutz-Green-Leaf-White-Stem-Beet.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Broccoli', 'Broccoli is a hardy vegetable that develops best during cool seasons of the year. Two crops per year (spring and fall) are possible in most parts of the country, especially with continuous improvement in fast maturity and heat tolerance that extends the life of broccoli through all but the hottest parts of the season. ', 1.5, 3.00,'part-shade','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwa55d033a/images/products/Waltham_Broccoli1.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Broccoli-purple', 'The Early Purple Sprouting broccoli is an heirloom broccoli bred for overwintering! This variety produces lots of beautiful purple broccoli sprouts in the spring. The Early Purple Sprouting grows slowly through the winter; very frost hardy.', 1.5, 3.00,'part-shade','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw54ec6d2b/images/products/Early-Purple-Sprouting-Broccoli-Seeds1.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Brussel Sprouts', 'Brussels sprouts are a member of the cabbage family and an excellent source of nutrients. Brussels sprouts thrive in full sun, and in rich, consistently moist soil. Brussels sprouts grow best in cool weather, but they will sprout from seed when soil temperatures are between 45 and 80 degrees. Because Brussels sprouts take a while to grow, it makes sense to get a jumpstart on growth by planting young plants.',4, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwaadf80b1/images/products/Brussel_Sprouts.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Burdock', 'The Chiko Burdock is a nutritious root with a curative medicinal property! Burdock is perfect for winter markets. The long roots of the burdock are among the hardiest of root vegetables, and not only overwinter in the garden easily for spring digging but also store well.', 2, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw87ee5741/images/products/Burdock-Seed1.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Cabbage', 'All forms of cabbage have succulent leaves that are free of hairs and covered with a waxy coating, which often gives the leaf surface a gray-green or blue-green colour. The plants grow best in mild to cool climates and tolerate frost; some forms tolerate hard freezing at certain periods of growth.', 1.5, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw7e53b00d/images/products/Stonehead-Cabbage-Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Carrot', 'The carrot is one of the most cultivated vegetables in the world. Its consumption has spreaded widely, since at present it is available all the year round. The part of the carrot that we consume is its root, of which there are various shapes and tastes. It stands out for its carotene and vitamin A, B and C content.', .5, 3.00, 'sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw07369b9a/images/products/Imperator-58-Carrot-Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Cauliflower', 'Cauliflowers are annual plants that reach about 1.5 feet tall and bear large rounded leaves that resemble collards (Brassica oleracea, variety acephala). As desired for food, the terminal cluster forms a firm, succulent “curd,” or head, that is an immature inflorescence (cluster of flowers).', 1.5, 3.00,'part-shade','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw6f188640/images/products/Amazing-Cauliflower1.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Celeriac', 'The Brilliant celeriac is a large round root related to celery! This celeriac plant produces a a large round root with dark green celery-like leaves and a white flesh. Brilliant is a great addition to any meal as it adds a great flavor!', 1.5, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw9d99f320/images/products/Brilliant-Celeriac-Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Celery', 'Celeriac is a root vegetable in the Parsley family. It is also. known as the turnip-rooted celery, a variety of celery that has been harvested specifically for its large, starchy root. It is harvested when it reaches about 4-6 inches in diameter and can be eaten raw or cooked.', 1.5, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwf976c0ac/images/products/Tall-Utah.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Chard', 'Chard is also called Swiss chard. The leaves and stalks are a good source of vitamins A, B, and C. Chard is popular as a home-garden plant because it is easy to grow, productive, and tolerant of moderate heat. Highly perishable, it is difficult to ship to distant markets.', 1, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw9784b995/images/products/Gold-Stem-Swiss-Chard-Seeds.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Chicory', 'Chicory, native to Europe and introduced into the United States late in the 19th century, chicory is cultivated extensively in the Netherlands, Belgium, France, and Germany and to some extent in North America. Its leaves are eaten as a vegetable or in a salad, and the roots may be boiled and eaten with butter. The plant is grown as a fodder or herbage crop for cattle. Chicory root can be roasted and ground to impart additional color, body, and bitterness to coffee; in the United States, this practice is especially popular in the city of New Orleans.', 1, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwb8cd5f63/images/products/Chicory.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Chinese Cabbage', 'Chinese cabbage is an important source of Vitamin C, which acts as a booster to the body''s defense mechanism. Vitamin C also helps the body fight various diseases and preventing infections such as Common cold and gum disease.', 1.5, 3.00,'part shade','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw6e6ea8a0/images/products/China-Coast-Cabbage.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Collards', 'Collards are erect, branched plants with thick stems and irregularly lobed dark green leaves with long petioles. The plant produces clusters of small yellow flowers on racemes. Collards can reach 3.3 ft in height and are usually grown as annuals, harvested after one growing season.', 1.5, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw2cbda6c7/images/products/Georgia_Southern_Collards.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Corn', 'Corn is an important crop in North America, since many animals raised for meat eat corn, not to mention the corn that people consume. In addition, products like high fructose corn syrup and ethanol fuel are made from corn. Many people also love to eat corn on the cob slathered with butter in the summer time.', 1, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw9012b2b7/images/products/Cadence-Corn-Seed.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Cucumber', 'Cucumbers are a type of edible plant that belongs to the gourd family. It''s widely cultivated and makes a nutritious addition to any diet. Cucumber is usually considered a vegetable because of how it''s used in the culinary world. However, as it grows from flowers and contains seeds, it''s botanically a fruit.', 5, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw33249ca7/images/products/Marketmore-76-Cucumber-Seed1.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Eggplant', 'Eggplant has antioxidants like vitamins A and C, which help protect your cells against damage. It''s also high in natural plant chemicals called polyphenols, which may help cells do a better job of processing sugar if you have diabetes.', 1.5, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwe1cc3e3f/images/products/Black-Beauty-Eggplant-Seeds.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Fennel', 'Fennel, a perennial herb of the carrot family (Apiaceae) grown for its edible shoots, leaves, and seeds. Native to southern Europe and Asia Minor, fennel is cultivated in temperate regions worldwide and is considered an invasive species in Australia and parts of the United States. All parts of the plant are aromatic and used in flavoring.', 1, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw0fb7f8da/images/products/Antares%20Fennel%20Seed.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Garlic', 'Garlic is widely recognized for its ability to fight bacteria, viruses, fungi, and even parasites. One study found that allicin, an active component of freshly crushed garlic, had antiviral properties and was also effective against a broad range of bacteria, including multidrug-resistant strains of E. coli.', .5, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwc8cc82a0/images/products/Spanish-Roja-Garlic-Cloves.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Gourd', 'Gourds are a warm season crop in the same family as squash, cucumbers, and melons. Native Americans used gourds practically for dishes and containers as well as ornamentally. Growing gourd plants is an interesting pursuit mainly because there are so many different types from which to choose.', 10, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwbe190b3b/images/products/Ten-Commandments-gourd-.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Green', 'The Old Fashioned Mustard Green is a real Southern treat! This green is a favorite that can be eaten fresh or cooked, but is best enjoyed either steamed or sauteed in our opinion! The Old Fashioned Mustard is easy to grow and care for, making it a great addition to any garden.', .5, 3.00,'part-shade','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw2ddc15d5/images/products/Old_Fashioned_Mustard.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Horseradish', 'Horseradish is a powerful root that is lip curling with a sting! Horseradish''s heat and biting flavor make it a quite popular ingredient in many dishes and amongst gardeners. The leaves on horseradish are also edible!', 1, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw35079133/images/products/Czechoslovokian-Horseradish.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Husk Cherry', 'Goldie is tasty heirloom husk cherry! This husk cherry ripens to a lovely orange and is best enjoyed in pies. Goldie is known for its very sweet flavor that does well in different types of jams and jellies. This low growing, very prolific vine husk cherry is a favorite!', 1.5, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw42c914b8/images/products/Ground-Cherry-Tomato-Seeds.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Kale', 'Kale plants produce a rosette of elongated leaves with wavy to frilled margins. The leaves are typically blue-green in colour but can also be light green, red, or purple, depending on the variety. In a long growing season the main stem reaches a height of 24 inches or more.', 1, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwdfe6d2ca/images/products/Scarlet-Kale.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Kohlrabi', 'The perfect choice for first-time kohlrabi growers as well as those kohlrabi veterans. Konan has a smooth, globe-shaped bulbs that can grow up to 6 inches in diameter and are the perfect upright size and shape for container gardening and garden plots.', 1.5, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw33a8b6f3/images/products/Kohlrabi_White_Vienna.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Leeks', 'King Richard is a newer leek variety that grows well throughout the United States. This leek variety is a summer type, non-bulbing leek that grows to 12" in length. King Richard has green leaves with white inside. This leek is a very early maturer and is not sufficient for overwinter growing.', 1, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw0852c26e/images/products/King-Richard-Leek.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Lettuce', 'Lettuce is one of the most widely consumed vegetables worldwide, but its nutritional value has been underestimated. Lettuce is low in calories, fat and sodium. It is a good source of fiber, iron, folate, and vitamin C. Lettuce is also a good source of various other health-beneficial bioactive compounds.', 1, 3.00,'sun','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw238fcaae/images/products/Garden-Lettuce-Mix-Seeds.jpg?sw=275&sh=275', '3,4,5,6,7,8,9'),
('Marigold-Flamenco French', 'The Flamenco Marigold is a compact French variety that blooms an array of fiery bright pastel yellows and reddish oranges! This variety is perfect for a container garden or flower bed as it is a very prolific and easy to grow annual. Flamenco is a great companion plant as it will attract many pollinators! You can enjoy these sunny blooms from mid spring all the way until the end of summer.', 2, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwc07f264c/images/products/Flamenco-Marigold.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),  
('Marjoram-Sweet', 'The delicious aroma of the Sweet Marjoram is similar to oregano or thyme, but has a sweeter fragrance that adds a mild and fresh taste to different dishes. This variety is a compact plant with beautiful, edible flowers, which have a mild and marjoram-like flavor, and can be used to garnish salads, soups, stews, sauces, and stuffing. Both the leaves and flowers of the Sweet Marjoram pairs well with citrus, mushrooms and fish.', 3, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw462c247f/images/products/Marjoram_Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Melon-Charentais Cantaloupe', 'The Charentais Melon is an old French heirloom with a superb flavor! This variety is a well known 2-3 lbs. heirloom melon that has light grey-green skin with a vibrant orange flesh. Charentais is one of the best tasting melons that is super sweet and very fragrant! This melon sells great at farmer''s markets.', 1.5, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw9a1d78a0/images/products/Charentais_Melon_Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Melon-Honeydew', 'The Honeydew Green Flesh Melon is perfect for any summer picnic or activity. This melon is specially adapted to grow in hot, long-summer climates, no matter how hot your summers get! This mid-sized Honeydew Green Flesh boasts some of the sweetest flavor to be found in the honeydew family. This melon is an all-around superb performer, it belongs in your vegetable patch this season!', 1.5, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw281ff64a/images/products/Organic-Honey-Dew-Stutz-Supreme-01.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Mint-Peppermint', 'The Peppermint has excellent leaves with a refreshing aromatic smell. Peppermint leaves are used as flavoring in baking, such as peppermint candies and teas. These plants are the perfect addition to any garden and can reach 3 feet tall.', 3, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwcba439e9/images/products/Peppermint-Seed-1.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Mint-Spearmint', 'The Peppermint has excellent leaves with a refreshing aromatic smell. Peppermint leaves are used as flavoring in baking, such as peppermint candies and teas. These plants are the perfect addition to any garden and can reach 3 feet tall.', 3, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw17478414/images/products/Spearmint-Seed-1.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Okra-Jambalaya', 'Just like its name, the Jambalaya Okra is the perfect okra for making jambalaya! This variety produces dark green, smaller and more tender pods! This okra is an extra-early maturing variety that boasts a very compact plant with small leaves. Jambalaya offers high yields of very uniform, shiny, dark green pods.', 1.5, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwb607042e/images/products/Jambalaya-Okra-Seeds1.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'), 
('Onion-Sweet Oversize', 'The Sweet Oversize Onion is just like its name, is oversized and super sweet! Get a head start with these oversized, sweet and delicious onion sets.', 4, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwc5396c62/images/products/IMG_6250_R1009-1.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Onion-Red Creole', 'The very sweet Red Creole Onion is the perfect variety for home gardens! This short day onion is great for the South and Mid-West climates and is also a good keeper. The solid, flat bulbs of the Red Creole has a spicy, red flesh that makes it a good cooking onion and is also great raw in salads.', 4, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwc356ba9f/images/products/Red-Creole-Onion-Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Onion-Texas Early Grano White', 'The Texas Early Grano Onion has a nice sweet flavor that is a favorite among home growers! The vidalia-type onion is now available in organic seeds. The white flesh is crisp and not too pungent. This short day onion variety is very disease resistant which makes it very popular for home growers and market growers alike. Certified Organic. Learn more about our organic seeds.', 4, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwe9cf8ec5/images/products/Texas-Early-Grano-502-Onion-Seeds.gif?sw=450&sh=450', '3,4,5,6,7,8,9'), 
('Oregano-Greek', 'The Greek Oregano is a popular herb with an excellent flavor that is a must for many Italian dishes like fish, pizza, tomato sauce and dressings. This perennial has a stronger and more aromatic fragrance than the common oregano and is known for its culinary and ornamental uses. Enjoy the Greek Oregano''s beautiful purple blooms all summer long!', 1, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw329285b9/images/products/Greek-Oregano.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Parsley-Italian Plain Leaf', 'The Italian Plain Leaf Parsley is an attractive parsley variety that used to garnish many dishes like fish, sauces or pastas! This parsley variety is our most familiar herb, widely employed as a culinary garnish for more than 2,000 years, but it is seldom eaten.', 1, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwd34c52e1/images/products/Italian-Flat-Leaf-Parsley-1.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Parsley-Triple Curled', 'The Triple Curled Parsley has beautifully intense triple curled leaves with dark green stems that look great as a garnish. This is a popular variety that is easy to grow, clean and harvest.', 1, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwc397ece5/images/products/Triple_Curled_Parsley_Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Pea-Super Sugar', 'The Super Sugar Pea is an improved original tall snap pea that is bursting with a sugary sweet flavor! This plant variety has a very high yield potential and even better flavor than before being improved, making it a favorite to add to many dishes.', 1, 3.00, 'Part-shade','https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwb9777517/images/products/Super-Sugar-Pea-Seeds1.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Pea-Early Frosty', 'The Early Frosty Pea is an old heirloom that, just like its name suggests, thrives in the colder climates. This variety does great in early spring or short season plantings. The vines are cold hardy and can grow to 30." This pea plant yields 3 1/2” pods filled with 6-7 delicious medium sized peas that are excellent for fresh eating or freezing for later use.', 1, 3.00, 'Part-shade', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw4227ba80/images/products/Early-Frosty-Pea-Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Pepper-Early Jalepeno', 'Get a head start with the early maturing Early Jalapeno Pepper. This pepper variety continuously produces a dark green, thick skin that forms to the shape of a cone. Enjoy the Early Jalapeno fresh or pickled on salads, dips or tacos!', 1.5, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw2d7898f4/images/products/Early-Jalapeno-Pepper-Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Pepper-Sunbright Bell', 'The Sunbright Pepper is a delicious and crispy bell pepper for home gardens. This pepper variety is a beautiful bright yellow bell pepper, with nice yields of sweet peppers. This colorful pepper is delicious and it will add a lot of color to your salads! The Sunbright is also the perfect pepper for stuffing.', 1.5, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw82ecc291/images/products/Sunbright-Pepper-Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Pepper-Tabasco', 'The Tabasco Pepper is a very hot pepper that is most known for its fantastic spicy flavor in hot sauces! This pepper variety turns green to red when mature and grows to a size of .5" x 1.5." Tabasco reaches 30,000+ Scovilles!', 1.5, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw66aea735/images/products/Tobasco-Pepper-Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Potato-Georgia Jets Sweet Potato', 'Certified - Georgia Jets is such a fast growing sweet potato! This sweet potato is a marvelous variety that just like its name suggests, matures extremely fast! In 90 days you will have large, ready to eat sweet potatoes. Georgia Jets is also high yielding!', 1.5, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw1f964ff9/images/products/Georgia-Jets-Sweet-Potato-Slips.jpg?sw=450&sh=450', '3,4,5,6,7,8,9') ,
('Potato-Red Pontiac', 'Certified - The easy and adaptable Red Pontiac Potato is perfect for home gardening. This variety is most likely the easiest and most adaptable red potato there is to grow, not to mention the consistent flavor! This potato has an attractive deep red skin and eyes, white flesh. This is the tuber of choice for new potatoes or fresh eating. The Red Pontiac came from Florida in 1945 and grows well in both the South and North regions.', 1.5, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwdaff5c36/images/products/Red-Pontiac-Seed-Potato-Cut1.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Potato-Russet Burbank', 'Certified - The Russet Burbank is the standard Idaho Potato variety that Idaho built its reputation on! Also known as the "Idaho Netted Gem" or simply just "The Russet". This variety is the most widely grown potato in the United States. We have eaten literally thousands of Russet Burbank potatoes baked, and the last one always tastes just as delicious as the first! Dr. Burbank, the Russet Burbank''s breeder, even admitted he was fortunate to have bred this popular cultivar!', 1, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw8523ba68/images/products/Russett-Seed-Potato-Cut1.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Potato-Yukon Gold', 'Certified - The Yukon Gold is a best seller and an excellent keeper! This favorite variety has attractive, smooth, thin yellow skin, shallow eyes with yellow flesh and uniform yields. If you like your fried potatoes golden brown, Yukon Gold will automatically almost always turn that color by themselves! Yukon Gold is also favored by top chefs for making traditional mashed potatoes, the ones that are made from the all American Russet potato. However, with Yukon Gold, your mashed potatoes are golden and beautiful to both the eye and the taste! When first harvested, Yukon Gold will show unique pink eyes not seen in other yellow varieties. They are best when home grown!', 1.5, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwac8b84ee/images/products/Yukon-Gold-Seed-Potato-Cut1.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Pumpkin-Halloween', 'Just like its name, the Halloween Pumpkin, or also known as the Jack''O Lantern, is the perfect porch decoration for Halloween! This variety is also a popular pumpkin standard. Halloween is an easy to grow pumpkin that will give you greatest patio decoration around!', 3, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwc228b76d/images/products/Halloween1.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Pumpkin-Fairytale', 'Fairytale is a traditional pumpkin variety from the south of France. This gorgeous, big flat fruit is heavily ribbed and looks similar to large wheels of cheese. This pumpkin averages 20 lbs. and ripens to a rich brown when fully ripe. The deep orange flesh is very fine grained, one of the best for baking! Long season.', 1.5, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw0922825b/images/products/Fairy-Tale-Pumpkin.png?sw=450&sh=450', '3,4,5,6,7,8,9'), 
('Pumpkin-Small Sugar', 'The Small Sugar''s thick, sweet flesh makes it a great choice to use in cooking and baking! This variety is an older, smaller pumpkin that is excellent in pies. Small Sugar is very fine-grained, sweet, sugary and keeps well.', 1.5, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwb9c0bb96/images/products/Small_Sugar.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Radish-Crunchy King', 'This variety has excellent shape and uniformity. It has bright white interior with attractive dark red skin and is mid-early maturing. Crunchy King holds its round shape and does well all season, but it is strongest in fall and spring slots. It has very high recovery and is slow to pith.', 1, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw3cc0e706/images/products/Country-King-Radish.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Raspberry-Latham Red', 'Outstanding Raspberry plant for home growing! Great for home growing, specially good for freezing and canning. Not as perishable as other varieties, it is easier to pick without crushing. Very heavy bearer, very hardy, adapts well to different kinds of soils.', 5, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw2fa6cd14/images/products/Latham-Raspberry-Plant.jpg?sw=450&sh=450', '4,5,6,7,8'),
('Rhubarb-Victoria', 'High yielding green stalks with red blush. Guaranteed to be the best cooking rhubarb you ever tasted! Victoria is sweeter and milder than other Rhubarbs. Stalks are slender and very tender, so it''s quick and easy to fix for the pot. Plants are high yielding; stalks green with red blush.', 3, 3.00, 'Sun', ' https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw3c1f6ff4/images/products/Victoria-Rhubarb-Seed.jpg?sw=450&sh=450', '4,5,6,7,8'),  
('Rosemary-Common', 'Rosemary is a very popular herb for its many uses, such as in potpourris and aromatherapy as well as flavoring many dishes! Start the seeds early indoors for a better harvest. Rosemary should be set outside early and will tolerate light frost.', 3, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw98638701/images/products/Rosemary-Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Sage-Broadleaf', 'The Broadleaf Sage is grown mainly for seasoning rich meats and sausages, as well as carrots, tomatoes, squash, corn and potatoes. This Sage has fragrant gray-green leaves and spikes of purple flowers.', 2, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw6b749d29/images/products/Sage-Seed.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Sage-White', 'Vary aromatic and white-green leaves. White sage has many herbal uses.', 2, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw86dc96ab/images/products/White-Sage-Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Spinach-Bloomsdale', 'The Bloomsdale spinach is such an attractive, tasty, and a popular garden standard spinach. This variety is an old favorite amongst gardeners. It has an excellent flavor and produces large quantities of tasty leaves. Bloomsdale is also very nutritious with lots of Vitamin A, C, and iron and is low in calories.', 2, 3.00, 'Part-shade', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwb137cedb/images/products/Bloomsdale.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Spinach-Seaside Baby', 'Seaside produces very uniform and great tasting baby leaf spinach. Stays baby size for extended period of time extending the season. Seaside has a nice, smooth, thick, very dark green, spade-shaped leaf making it a perfect choice for baby leaf growers. Seaside has great downy mildew resistance.', 2, 3.00, 'Part-Shade', ' https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwc09ee736/images/products/Seaside%20Spinach%20Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'), 
('Sprouts-True Watercress', 'True Watercress is a delicious highly nutritious aquatic herb. This watercress has a wonderful fresh peppery-tasting flavor. Being semiaquatic, this cress is a creeping perennial whose leaves are popular in salads, sandwiches and as a garnish. True Watercress grow rapidly in in damp soil and can be grown in pots of soil placed in a tub of water if water is changed weekly.', 1, 3.00, 'Shade', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwe54735cc/images/products/True_Cress_Seed.jpg?sw=450&sh=450','3,4,5,6,7,8,9'),  
('Sprouts-Rainbow Quinoa', 'The Brilliant Rainbow Quinoa blends beautifully into meals or salads. Just like its name, this quinoa contains a spectrum of many different colored heads - red, orange, gold, white, and green. The Brilliant Rainbow Quinoa''s leaves have a salty spinach-like flavor. Harvest for greens when 6-8" tall or let grow for beautiful tall blooms that can be harvested for grain. This Quinoa''s grain has a nutty flavor that goes well with any dish!', 1, 3.00, 'Shade', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwf6dd2777/images/products/Quinoa-Rainbow-Green-Seeds.jpg?sw=450&sh=450','3,4,5,6,7,8,9'),    
('Squash-Dark Green Zucchini', 'The Dark Green Zucchini is the darkest and most tender zucchini we have! This variety has a smooth, straight, green outer skin with a creamy white flesh. Pick at 6-8" for an even more tender flesh, that is perfect for baking into stews or making zucchini bread.', 3, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw24616637/images/products/Dark-Green-Zucchini.jpg?sw=450&sh=450','3,4,5,6,7,8,9'),
('Squash-Golden', 'High yielding squash. Smooth, straight, cucumber size. Great when picked young. Yellow skin with pale flesh.', 4, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwed809d32/images/products/Golden-Zucchini-Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Squash-Vegetable Spaghetti', 'True to its name, the Vegetable Spaghetti Squash allows you to grow your own spaghetti noodles! This bright yellow squash is great to use as a healthy, tasty replacement for "noodles" in various meals. The Vegetable Spaghetti produces its noodles within its flesh inside of itself when cooked.', 3, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwe1d27859/images/products/Vegetable-Spaghetti-Squash.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Strawberry-Giant', 'Very large fruits with juicy flesh! These large growing strawberries are the largest on the market. Great flavor. Perfect for farmers markets.', 2, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw04f207d1/images/products/Giant-Strawberry-Seeds-3.jpg?sw=450&sh=450', '4,5,6,7,8'),
('Swiss Chard-Rainbow Blend', 'The Rainbow Blend Swiss Chard will brighten up any dish! The beautifully colored and delicious Rainbow Blend is a mixture of different red, orange, pink, yellow and white chard. These stunning leafy greens are a staple to any garden or meal. The glossy dark green leaves have a crisp texture that can''t be beat. Certified Organic. Learn more about our organic seeds.', 1.5, 3.00, 'Part-shade', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwf3718fe4/images/products/Organic-rainbow-blend-chard.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Tarragon-French', 'French tarragon is a loose, open perennial growing to about two to three feet tall. Leaves are dark green, narrow and slightly twisted. Plant will occasionally produce small, greenish flowers that are sterile. Leaves have a licorice or anise flavor.', 2, 3.00, 'Sun', ' https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw67dda26a/images/products/Tarragon.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'), 
('Tarragon-Mexican', 'Culinary and medicinal as well as an ornamental herb. May replace French tarragon with similar aroma and overall appearance. Soft oval gray-green leaves, about 7cm long. Hardy perennial bush with an upright growing habit. Blooms late summer with clusters of golden flowers. A warm weather plant, performs best in full light.', 3, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw9f508952/images/products/Mexican-Tarragon.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Thyme-English', 'The English Thyme is a beautiful purple-gray flowering herb that brings out a great flavor when added to different dishes. This herb grows tall and wide and if allowed to flower, will bring butterflies and bees to the garden. English Thyme is commonly used for seasoning either fresh or dried.',  1, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwed0590e1/images/products/English-Thyme-Seed.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Thyme-French', 'The French Thyme is a popular herb used to add flavor in poultry and fishes dishes as well as salads, stews, sauces and pickles! This Thyme variety produces very aromatic blue-green leaves with pale lavender flowers that will add a pop of beautiful color to any garden or windowsill.',  1, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw34bcda9a/images/products/French-Thyme-Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Thyme-Creeping', 'The Creeping Thyme is a mat-forming evergreen plant that produces small purple spikes and makes a beautiful ground cover! This "walk on" hardy perennial not only adds a beautiful pop of color to the garden, but it also gives off a wonderful fragrance that is perfect in a bouquet.', 3, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwfea8f4b9/images/products/Creeping-Thyme-Seed.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Tomato-Cherokee Purple', 'The Cherokee Purple is an old heirloom tomato that has an outstanding flavor. This tomato dates back to pre-1890 and is recognized as an old Cherokee Indian heirloom that originated in Tennessee. This variety has a semi-meaty flesh with an average seed/flesh ratio. The Cherokee Purple offers some of the best flavor with an earthy-sweet, rich taste that is delicious eaten raw. This tomato has a beautiful purple skin with a slight pinkish-red hue. This plant produces large vines with large beefsteak fruits that average 8-20 ounces. The Cherokee Purple is an indeterminate tomato that will keep producing all summer long and into the first frost in fall time. This high yielding tomato is in our top 5 of best heirloom tomatoes on the market!', 3, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw8bb7d914/images/products/Tomato_Cherokee-Purple.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'), 
('Tomato-Kelloggs Breakfast', 'The Kellogg''s Breakfast Tomato is an heirloom variety that produces big, bright orange fruits that are meaty and juicy with only a few seeds! This large tomato can weigh 1 pound or more! This variety has thin skin and a sweet tangy flavor. Kellogg''s Breakfast will brighten up your day!', 3, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw4ed05ba0/images/products/Kelloggs_Beefsteak_Tomatoes1.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'), 
('Tomato-Baby Roma', 'The Baby Roma, also known as the "Cherry Roma," is a miniature roma-shaped tomato that is bursting with an intense sweet flavor. This tomato variety is great for garden snacking, adding into salads and growing for market production. The Baby Roma plant produces an incredibly heavy set of 1” grape-type tomato fruits that have a very long shelf life. ', 3, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwe920805e/images/products/Organic-Baby-Roma-Tomato-Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),  
('Tomato-Big Beef', 'The Big Beef Tomato is an All American Selection winner beefsteak tomato variety that has been a farm favorite for a reason! This tomato variety produces delicious 12 ounce, deep oblate to globe shaped red fruits. This high yielding, high quality tomato is crack and highly disease resistant.', 3, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dwfd7f2eb6/images/products/Big-Beef-Tomato-1.jpg?sw=450&sh=450', '3,4,5,6,7,8,9'),
('Turnip-Purple Top', 'The Purple Top White Globe Turnip is a beautifully purple and white colored turnip that is the best tasting turnip around! This turnip variety has a fine grained root that can grow as big as a baseball! The popular Purple Top White Globe is an excellent yielding turnip that is a great fall crop that gets even better with cold weather.', 4, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw9f5f32f2/images/products/Purple-Top-White-Globe-Turnips.jpg?sw=450&sh=450','3,4,5,6,7,8,9'), 
('Watermelon-Harvest Moon Seedless', 'The Harvest Moon Seedless is a seedless Moon and Stars watermelon type! This variety is a new twist on the old favorite with a dark green rind with characteristic markings of small yellow "stars" and larger yellow "moons." This watermelon has a crisp, sweet red flesh is seedless with an excellent flavor. The Harvest Moon Seedless Watermelon is earlier to ripen with shorter vines and a higher yield of smaller melons than the heirloom Moon and Stars. This medium-sized, 8-13 lb. oval watermelon averages 2-3 fruits per plant.', 3, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw3662acd4/images/products/Harvest-Moon-Watermelon.png?sw=450&sh=450','3,4,5,6,7,8,9'),
('Watermelon-All Sweet', 'The All Sweet Watermelon has a firm, crisp flesh that is, just like in its name, very sweet! This is a great watermelon for warmer areas. The All Sweet is the perfect addition to any garden if you are looking for a sweet flavor with a great texture.', 3, 3.00, 'Sun', 'https://www.ufseeds.com/dw/image/v2/BFKV_PRD/on/demandware.static/-/Sites-master-urbanfarmer/default/dw31116792/images/products/All_Sweet_Watermelon_Seeds.jpg?sw=450&sh=450', '3,4,5,6,7,8,9');    


GO

